return {
  {
    "rose-pine/neovim",
    name = "rose-pine",
    priority = 1000,
    opts = {
      variant = "moon",
      dark_variant = "moon",
      dim_inactive_windows = true,
      extend_background_behind_borders = true,
      styles = {
        bold = true,
        italic = true,
        transparency = false,
      },
      palette = {
        moon = {
          base = "#17152b",
          surface = "#201d38",
          overlay = "#2d294a",
          muted = "#817a9f",
          subtle = "#aaa3c9",
          text = "#eeeaff",
          love = "#ff7eb6",
          gold = "#efc2ff",
          rose = "#f5a3c7",
          pine = "#9b8cff",
          foam = "#a9c7ff",
          iris = "#c6a7ff",
          leaf = "#9bd7c5",
          highlight_low = "#211e3a",
          highlight_med = "#342f55",
          highlight_high = "#4a426d",
        },
      },
      highlight_groups = {
        CursorLine = { bg = "highlight_low" },
        CursorLineNr = { fg = "rose", bold = true },
        Visual = { bg = "highlight_med" },
        FloatBorder = { fg = "iris", bg = "surface" },
        NormalFloat = { bg = "surface" },
        Pmenu = { bg = "surface" },
        PmenuSel = { fg = "text", bg = "highlight_med", bold = true },
        Search = { fg = "base", bg = "rose", bold = true },
        IncSearch = { fg = "base", bg = "iris", bold = true },
        DiagnosticVirtualTextError = { fg = "love" },
        DiagnosticVirtualTextWarn = { fg = "gold" },
        DiagnosticVirtualTextInfo = { fg = "foam" },
        DiagnosticVirtualTextHint = { fg = "iris" },
        SnacksDashboardHeader = { fg = "iris", bold = true },
        SnacksDashboardIcon = { fg = "rose" },
        SnacksDashboardKey = { fg = "love", bold = true },
        SnacksDashboardDesc = { fg = "text" },
        SnacksDashboardSpecial = { fg = "foam" },
        SnacksNotifierBorderInfo = { fg = "iris" },
        SnacksNotifierTitleInfo = { fg = "rose", bold = true },
      },
    },
  },

  {
    "LazyVim/LazyVim",
    opts = {
      colorscheme = "rose-pine-moon",
    },
  },
}
